# Generated by Django 5.0.2 on 2024-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
