# Generated by Django 5.0.2 on 2024-03-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0002_scan_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBuilbing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('scan', models.FileField(upload_to='scan/')),
                ('object_builbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCR_scan.objectbuilbing')),
            ],
        ),
    ]
