# Generated by Django 5.0.2 on 2024-03-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0003_objectbuilbing_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='title',
        ),
    ]
