# Generated by Django 5.0.2 on 2024-03-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0004_remove_download_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('len_files', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OCR_scan.task'),
        ),
    ]
