# Generated by Django 5.0.2 on 2024-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0006_remove_download_scan_remove_scan_object_builbing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
