# Generated by Django 5.0.2 on 2024-03-05 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0007_alter_task_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='date_building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OCR_scan.datebuilding'),
            preserve_default=False,
        ),
    ]
