# Generated by Django 5.0.2 on 2024-03-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0008_datebuilding_download_date_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='date_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCR_scan.datebuilding', verbose_name='Дата строительства'),
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scan/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='download',
            name='object_builbing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCR_scan.objectbuilbing', verbose_name='Объект строительства'),
        ),
    ]
