# Generated by Django 5.0.2 on 2024-03-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0009_alter_download_date_building_alter_download_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='cover',
            field=models.ImageField(max_length=2000, upload_to='images/'),
        ),
    ]
