# Generated by Django 5.0.2 on 2024-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_scan', '0010_alter_scan_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
